import { Router } from 'express';
import { authRouter } from '../features/auth/auth.js';
import { categoriesRouter } from '../features/categories/categories.js';
import { productsRouter } from '../features/products/products.js';
import { inventoryRouter } from '../features/inventory/inventory.js';
import { dashboardRouter } from '../features/dashboard/dashboard.js';
import { reportsRouter } from '../features/reports/reports.js';
import { usersRouter } from '../features/users/users.js';
export const apiRouter = Router();
apiRouter.use('/auth', authRouter);
apiRouter.use('/categories', categoriesRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/users', usersRouter);
